### ISSUE TITLE
About merged_data_new.json

### ISSUE THREAD

**Issue by haibo-qiu** [Pointcept/PointBLIP#5]
Hi, thank you for your excellent open-source work.

When attempting to run the training, I noticed that `lavis/datasets/datasets/objaverse_caption_datasets.py` requires two files: `merged_data_new.json` and `overal_description_merged.json`. However, in the ULIP 2 [data](https://console.cloud.google.com/storage/browser/sfr-ulip-code-release-research/ULIP-Objaverse_triplets?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false), I only found a file named `merged_data.json`. Are these files the same? Or did I overlook any new files?

Furthermore, do you have any plans to release the paper or technical report about this repository? Thank you once again.

**Comment by Qi-Zhangyang** [comment]
We will release our technical report in this week and will update the code to solve your problem.
Thanks for your question.

**Comment by haibo-qiu** [comment]
Thank you for your response.
Looking forward to your technical report.
